Issue #304: Buttons in Layout-Form-Row zentrieren
IHK-GfI/lux-components pull request #311
Opened 2023-04-20 07:57 UTC by patrowe

-Buttons zentriert
-neue Properties formNoTopLabel und formNotBottomLabel in der row-item-config einegführt 
-Beispiel in der Demo angepasst

Bitte Testen!

2023-04-20 10:46 UTC, thodic77 requested changes
Bitte die `markdownDataXXX` in `htmlDataXXX` umbenennen.

2023-04-20 12:40 UTC, patrowe commented
Die Variablen wurden umbenannt.

2023-04-20 12:42 UTC, thodic77 approved these changes

2023-04-24 06:05 UTC, thodic77 approved these changes

2023-04-24 06:12 UTC, merged