Issue_26: Neue Features für lux‐autocomplete
IHK-GfI/lux-components pull request #36
Opened 2020-09-08 11:30 UTC by thodic77

- Property luxPickValue hinzugefügt.

2020-09-11 10:41 UTC, realSchoki commented on src/app/demo/components-overview/autocomplete-example/autocomplete-example.component.ts
> -    { label: 'Option #1', short: 'O1', value: '#1' },
Das Beispiel bitte weiter mir 'short' anbieten, da sonst das Feature im Beispielprojekt nicht mehr klappt, wenn:
-> luxOptionLabelProp
-> Bezeichnung (kurz)
eingestellt wird.

2020-09-11 10:42 UTC, realSchoki requested changes
Siehe meine Anmerkung in 
src/app/demo/components-overview/autocomplete-example/autocomplete-example.component.ts

2020-09-14 07:14 UTC, thodic77 commented on src/app/demo/components-overview/autocomplete-example/autocomplete-example.component.ts
> -    { label: 'Option #1', short: 'O1', value: '#1' },
Ich habe das Property 'short' wieder hinzugefügt.

2020-09-17 12:38 UTC, a-erinola commented
Erfolgreich getestet.

2020-09-17 12:38 UTC, merged